export const LOADBLOG_SUCESS="LOADBLOG_SUCESS";
export const LOADBLOG_FAIL="LOADBLOG_FAIL";
export const GETMYBLOGS_SUCESS="GETMYBLOGS_SUCESS";
export const GETMYBLOGS_FAIL="GETMYBLOGS_FAIL";
export const ADDBLOG_SUCESS="ADDBLOG_SUCESS";
export const ADDBLOG_FAIL="ADDBLOG_FAIL";
export const REMOVEBLOG_SUCESS="REMOVEBLOG_SUCESS";
export const REMOVEBLOG_FAIL="RMOVEBLOG_FAIL";